### PR TITLE
small bugfixes

### PR DESCRIPTION
**Pull request by roman204**
fixed install problems and add author name

### CODE REVIEW

**Comment by GordonLesti** [comment]
Hello @roman204
I am on vacation at the moment. Do you may want permissions to merge? I could also transfer the repo to you.

**Comment by roman204** [comment]
Hy Gordon,
you can give me perms or transfer, like you want it.


2017-03-16 10:17 GMT+01:00 Gordon Lesti <notifications@github.com>:

**Comment by GordonLesti** [comment]
@roman204 I have invited you as collaborator. Next month we can transfer the repo if you want to.

**Comment by GordonLesti** [comment]
@roman204 Are you able to merge your own PR?

**Comment by roman204** [comment]
worked, thanks gordon.

**Pull request merged**
